Repository wrtnlabs/autobe, pull requests merged in 2025-08, with the labels that each got.

#310 feat(*): fix license in CLAUDE.md
  CLAUDE.md
Labels: bug, documentation

#301 Fix(agent): Fix the tool description of orchestratePrismaComponent
  packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
Labels: enhancement

#314 fix(*): update dependencies especiall typescript.
  internals/dependencies/nestjs/package-lock.json
  internals/dependencies/nestjs/package.json
  internals/dependencies/test/package-lock.json
  internals/dependencies/test/package.json
  internals/template/realize/package.json
  internals/template/test/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  website/package.json
Labels: bug, enhancement

#315 feat(prisma): add thinking concept to prisma components.
  packages/agent/prompts/PRISMA_COMPONENT.md
  packages/agent/prompts/PRISMA_SCHEMA.md
  packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
  packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaComponentsApplication.ts
  packages/interface/src/events/AutoBePrismaComponentsEvent.ts
  packages/interface/src/prisma/AutoBePrisma.ts
  test/assets/histories/openai/gpt-4.1/bbs-backend.prisma.components.json
  test/assets/histories/openai/gpt-4.1/shopping-backend.prisma.components.json
  test/src/features/prisma/test_agent_prisma_components_shopping.ts
Labels: documentation, enhancement

#316 feat(agent): add thinking concept to prisma schemas.
  packages/agent/prompts/PRISMA_COMPONENT.md
  packages/agent/prompts/PRISMA_SCHEMA.md
  packages/agent/src/factory/createAutoBeApplication.ts
  packages/agent/src/orchestrate/prisma/orchestratePrisma.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts
  packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaComponentApplication.ts
  packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaSchemaApplication.ts
  packages/interface/src/events/AutoBePrismaInsufficientEvent.ts
  packages/interface/src/events/AutoBePrismaSchemasEvent.ts
  test/assets/histories/openai/gpt-4.1/bbs-backend.prisma.schemas.json
  test/assets/histories/openai/gpt-4.1/shopping-backend.prisma.schemas.json
  test/src/features/prisma/internal/validate_agent_prisma_main.ts
  test/src/features/prisma/internal/validate_agent_prisma_schemas.ts
  test/src/features/prisma/test_agent_prisma_schemas_shopping.ts
Labels: documentation, enhancement

#317 feat(agent): finalize prisma corrector.
  README.md
  packages/agent/src/orchestrate/prisma/histories/transformPrismaComponentsHistories.ts
  packages/agent/src/orchestrate/prisma/histories/transformPrismaCorrectHistories.ts
  packages/agent/src/orchestrate/prisma/histories/transformPrismaHistories.ts
  packages/agent/src/orchestrate/prisma/histories/transformPrismaSchemaHistories.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts
  packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaCorrectApplication.ts
  test/assets/histories/openai/gpt-4.1/bbs-backend.prisma.json
  test/assets/histories/openai/gpt-4.1/bbs-backend.prisma.snapshots.json
Labels: enhancement

#322 feat(agent): let prisma and interface agents to write only english
  packages/agent/prompts/INTERFACE_COMPLEMENT.md
  packages/agent/prompts/INTERFACE_ENDPOINT.md
  packages/agent/prompts/INTERFACE_GROUP.md
  packages/agent/prompts/INTERFACE_OPERATION.md
  packages/agent/prompts/INTERFACE_SCHEMA.md
  packages/agent/prompts/PRISMA.md
  packages/agent/prompts/PRISMA_CORRECT.md
  packages/agent/prompts/PRISMA_SCHEMA.md
  packages/agent/src/orchestrate/prisma/histories/transformPrismaHistories.ts
  packages/interface/src/openapi/AutoBeOpenApi.ts
  packages/interface/src/prisma/AutoBePrisma.ts
Labels: documentation, enhancement

#325 feat(prisma): draft and final, all of them are AST.
  packages/agent/prompts/PRISMA_SCHEMA.md
  packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts
  packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaSchemaApplication.ts
  packages/interface/src/events/AutoBePrismaSchemasEvent.ts
Labels: documentation, enhancement

#327 feat(agent): restore prisma agent by context size
  CLAUDE.md
  packages/agent/prompts/PRISMA_SCHEMA.md
  packages/agent/src/context/AutoBeTokenUsage.ts
  packages/agent/src/context/AutoBeTokenUsageComponent.ts
  packages/agent/src/orchestrate/prisma/histories/transformPrismaSchemaHistories.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts
  packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaSchemaApplication.ts
  packages/interface/src/events/AutoBePrismaSchemasEvent.ts
  test/src/TestFactory.ts
  test/src/features/analyze/internal/validate_agent_analyze_main.ts
  test/src/features/interface/internal/prepare_agent_interface.ts
  test/src/features/interface/internal/validate_agent_interface_main.ts
  test/src/features/prisma/internal/prepare_agent_prisma.ts
  test/src/features/prisma/internal/validate_agent_prisma_main.ts
  test/src/features/realize/internal/prepare_agent_realize.ts
  test/src/features/realize/internal/validate_agent_realize_main.ts
  test/src/features/test/internal/prepare_agent_test.ts
  test/src/index.ts
Labels: bug, enhancement

#329 feat(agent): optimize `AutoBePrismaSchemasEvent` related
  packages/agent/prompts/PRISMA_SCHEMA.md
  packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts
  packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaSchemaApplication.ts
  packages/interface/src/events/AutoBePrismaSchemasEvent.ts
  test/src/features/prisma/internal/validate_agent_prisma_main.ts
Labels: documentation, enhancement

#334 feat(agent): make function calling schema type safely.
  internals/dependencies/nestjs/package-lock.json
  internals/dependencies/nestjs/package.json
  internals/dependencies/test/package-lock.json
  internals/dependencies/test/package.json
  internals/template/realize/package.json
  internals/template/test/package.json
  packages/agent/src/factory/createAutoBeApplication.ts
  packages/agent/src/orchestrate/analyze/orchestrateAnalyzeComposer.ts
  packages/agent/src/orchestrate/analyze/orchestrateAnalyzeReviewer.ts
  packages/agent/src/orchestrate/analyze/orchestrateAnalyzeWrite.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceEndpoints.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceGroups.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperationReview.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
  packages/agent/src/orchestrate/interface/structures/IAutoBeInterfaceOperationReviewApplication.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts
  packages/agent/src/orchestrate/realize/histories/transformRealizeAuthorization.ts
  packages/agent/src/orchestrate/realize/histories/transformRealizeAuthorizationCorrectHistories.ts
  packages/agent/src/orchestrate/realize/histories/transformRealizeCoderHistories.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorization.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorizationCorrect.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeCoder.ts
  packages/agent/src/orchestrate/test/experimental/orchestrateTestCorrect.ast
  packages/agent/src/orchestrate/test/experimental/orchestrateTestWrite.ast
  packages/agent/src/orchestrate/test/histories/transformTestCorrectHistories.ts
  packages/agent/src/orchestrate/test/histories/transformTestHistories.ts
  packages/agent/src/orchestrate/test/histories/transformTestScenarioHistories.ts
  packages/agent/src/orchestrate/test/histories/transformTestWriteHistories.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
  packages/interface/src/events/AutoBePrismaInsufficientEvent.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/src/features/prisma/internal/validate_agent_prisma_schemas.ts
Labels: bug, documentation, enhancement

#341 fix(playground): exact audio base64 format
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatBodyMovie.tsx
Labels: bug

#344 feat(playground): refactoring file uploader and voice recorder.
  packages/playground-ui/src/contexts/AutoBePlaygroundDragContext.tsx
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatBodyMovie.tsx
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatPromptMovie.tsx
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatUploadMovie.tsx
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatVoiceMovie.tsx
  packages/playground-ui/src/structures/IAutoBePlaygroundBucket.ts
  packages/playground-ui/src/structures/IAutoBePlaygroundUploadConfig.ts
  packages/playground-ui/src/utils/AutoBePlaygroundFileUploader.ts
  packages/playground-ui/src/utils/AutoBePlaygroundVoiceRecorder.ts
Labels: documentation, enhancement

#345 feat(agent): mock agent's sleepMap updating
  packages/agent/src/AutoBeMockAgent.ts
  packages/playground-ui/src/movies/configure/AutoBePlaygroundConfigureMovie.tsx
Labels: enhancement

#354 fix(agent): no more reference option require for AI schemas.
  packages/agent/src/factory/createAutoBeApplication.ts
  packages/agent/src/orchestrate/analyze/orchestrateAnalyzeReviewer.ts
  packages/agent/src/orchestrate/analyze/orchestrateAnalyzeScenario.ts
  packages/agent/src/orchestrate/analyze/orchestrateAnalyzeWrite.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceAuthorization.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceEndpoints.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaReview.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorization.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorizationCorrect.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeCoder.ts
  packages/agent/src/orchestrate/test/experimental/orchestrateTestCorrect.ast
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
Labels: bug, documentation, enhancement

#355 fix(playground): exact supported extensions
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatUploadMovie.tsx
  packages/playground-ui/src/utils/AutoBePlaygroundFileUploader.ts
Labels: bug, enhancement

#363 fix(playground): exact prompt button disabling
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatPromptMovie.tsx
Labels: bug

#374 fix(compiler): block description comment tag
  internals/dependencies/nestjs/package-lock.json
  internals/dependencies/nestjs/package.json
  internals/dependencies/test/package-lock.json
  internals/dependencies/test/package.json
  internals/template/realize/package.json
  internals/template/test/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#373 fix(agent): interface agent to validate unique accessor
  packages/agent/prompts/INTERFACE_ENDPOINT.md
  packages/agent/prompts/INTERFACE_OPERATION.md
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/interface/src/openapi/AutoBeOpenApi.ts
Labels: bug, enhancement

#377 feat(interface): correct invalid function name
  packages/agent/prompts/INTERFACE_OPERATION.md
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/interface/src/openapi/AutoBeOpenApi.ts
Labels: bug, documentation, enhancement

#382 feat(test): simplify event listener functions
  packages/vscode-extension/interface/src/message.dto.ts
  test/src/features/analyze/internal/validate_agent_analyze_main.ts
  test/src/features/interface/internal/validate_agent_interface_main.ts
  test/src/features/prisma/internal/validate_agent_prisma_main.ts
  test/src/features/realize/internal/validate_agent_realize_main.ts
  test/src/features/test/internal/validate_agent_test_main.ts
Labels: enhancement

#391 feat(agent): embed `forceRetry` in the context.
  packages/agent/src/factory/createAutoBeContext.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaReview.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeCorrect.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeWrite.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
  packages/agent/src/utils/forceRetry.ts
Labels: enhancement

#392 fix(agent): no more forceRetry be used in each workflow
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperationsReview.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemasReview.ts
Labels: bug, enhancement

#396 feat(interface): vendor request/response events
  packages/agent/src/AutoBeAgent.ts
  packages/agent/src/AutoBeMockAgent.ts
  packages/agent/src/factory/createAutoBeContext.ts
  packages/interface/src/events/AutoBeEvent.ts
  packages/interface/src/events/AutoBeEventSource.ts
  packages/interface/src/events/AutoBeRequestEvent.ts
  packages/interface/src/events/AutoBeVendorRequestEvent.ts
  packages/interface/src/events/AutoBeVendorResponseEvent.ts
  packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
  test/src/features/typings/test_typing_rpc_listener_functions.ts
Labels: documentation, enhancement

#399 fix(test): wrong token usage tracing on archiver.
  test/src/executable/archive.ts
  test/src/features/interface/internal/validate_agent_interface_main.ts
  test/src/features/prisma/internal/validate_agent_prisma_main.ts
  test/src/features/realize/internal/validate_agent_realize_main.ts
  test/src/features/test/internal/validate_agent_test_main.ts
  test/src/internal/TestHistory.ts
Labels: bug, enhancement

#415 feat(agent): reverse what to do and not to do
  packages/agent/prompts/ANALYZE_REVIEW.md
  packages/agent/prompts/ANALYZE_WRITE.md
  packages/agent/prompts/INTERFACE_AUTHORIZATION.md
  packages/agent/prompts/INTERFACE_COMPLEMENT.md
  packages/agent/prompts/INTERFACE_ENDPOINT.md
  packages/agent/prompts/INTERFACE_GROUP.md
  packages/agent/prompts/INTERFACE_OPERATION.md
  packages/agent/prompts/INTERFACE_OPERATION_REVIEW.md
  packages/agent/prompts/INTERFACE_SCHEMA.md
  packages/agent/prompts/INTERFACE_SCHEMA_REVIEW.md
  packages/agent/prompts/PRISMA_COMPONENT.md
  packages/agent/prompts/PRISMA_CORRECT.md
  packages/agent/prompts/PRISMA_REVIEW.md
  packages/agent/prompts/PRISMA_SCHEMA.md
  packages/agent/prompts/REALIZE_AUTHORIZATION.md
  packages/agent/prompts/REALIZE_AUTHORIZATION_CORRECT.md
  packages/agent/prompts/REALIZE_CODER.md
  packages/agent/prompts/TEST_CORRECT.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_WRITE.md
Labels: documentation

#418 feat(agent): system prompt tuning a little bit
  packages/agent/prompts/ANALYZE_REVIEW.md
  packages/agent/prompts/ANALYZE_WRITE.md
  packages/agent/prompts/INTERFACE_AUTHORIZATION.md
  packages/agent/prompts/INTERFACE_COMPLEMENT.md
  packages/agent/prompts/INTERFACE_ENDPOINT.md
  packages/agent/prompts/INTERFACE_GROUP.md
  packages/agent/prompts/INTERFACE_OPERATION.md
  packages/agent/prompts/INTERFACE_OPERATION_REVIEW.md
  packages/agent/prompts/INTERFACE_SCHEMA.md
  packages/agent/prompts/INTERFACE_SCHEMA_REVIEW.md
  packages/agent/prompts/PRISMA_COMPONENT.md
  packages/agent/prompts/PRISMA_CORRECT.md
  packages/agent/prompts/PRISMA_REVIEW.md
  packages/agent/prompts/PRISMA_SCHEMA.md
  packages/agent/prompts/REALIZE_AUTHORIZATION.md
  packages/agent/prompts/REALIZE_AUTHORIZATION_CORRECT.md
  packages/agent/prompts/REALIZE_CODER.md
  packages/agent/prompts/TEST_CORRECT.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/factory/createAutoBeContext.ts
  test/src/internal/TestHistory.ts
Labels: documentation

#419 fix(compiler): prisma's duplicated names between field and relations
  packages/agent/src/factory/createAutoBeContext.ts
  packages/compiler/src/prisma/validatePrismaApplication.ts
Labels: bug, documentation, enhancement

#441 feat(agent): stop tracing createAutoBeContext
  packages/agent/src/factory/createAutoBeContext.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  test/assets/histories/openai/gpt-4.1/todo-backend.analyze.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.analyze.reviews.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.analyze.scenario.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.analyze.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.analyze.writes.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.interface.endpoints.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.interface.groups.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.interface.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.interface.operations.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.interface.schemas.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.interface.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.prisma.json.gz
  test/assets/histories/openai/gpt-4.1/todo-backend.prisma.snapshots.json.gz
Labels: bug, enhancement

#457 feat(compiler): support `@setHeader` tag from `@nestia/migrate`
  internals/dependencies/nestjs/package-lock.json
  internals/dependencies/nestjs/package.json
  internals/dependencies/test/package-lock.json
  internals/dependencies/test/package.json
  internals/template/realize/package.json
  internals/template/test/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#458 fix(agent): block duplicated operation
  packages/agent/src/orchestrate/interface/orchestrateInterface.ts
Labels: bug

#454 fix(agent): Add Authorization Logic to Test Scenario Agent
  packages/agent/prompts/INTERFACE_AUTHORIZATION.md
  packages/agent/prompts/INTERFACE_ENDPOINT.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/src/factory/createAutoBeContext.ts
  packages/agent/src/orchestrate/interface/histories/transformInterfaceEndpointHistories.ts
  packages/agent/src/orchestrate/interface/histories/transformInterfaceOperationsReviewHistories.ts
  packages/agent/src/orchestrate/interface/histories/transformInterfaceSchemasReviewHistories.ts
  packages/agent/src/orchestrate/interface/orchestrateInterface.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceAuthorizations.ts
  packages/agent/src/orchestrate/realize/histories/transformRealizeAuthorization.ts
  packages/agent/src/orchestrate/realize/histories/transformRealizeAuthorizationCorrectHistories.ts
  packages/agent/src/orchestrate/realize/histories/transformRealizeCorrectHistories.ts
  packages/agent/src/orchestrate/test/histories/transformTestScenarioHistories.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestScenarioAuthorizationRole.ts
  packages/compiler/src/prisma/validatePrismaApplication.ts
  packages/compiler/src/prisma/writePrismaApplication.ts
  packages/interface/src/events/AutoBeInterfaceCompleteEvent.ts
  packages/interface/src/histories/AutoBeInterfaceHistory.ts
  packages/interface/src/histories/contents/AutoBeInterfaceAuthorization.ts
  packages/interface/src/histories/contents/index.ts
  packages/utils/src/MapUtil.ts
  packages/utils/src/index.ts
  test/src/features/interface/internal/validate_agent_interface_authorizations.ts
Labels: enhancement

#467 fix(ui): wrong command
  packages/ui/package.json
Labels: bug

#468 fix(agent): Fix Authorization Runtime Error
  internals/template/realize/src/providers/authorize/jwtAuthorize.ts
  packages/agent/prompts/REALIZE_AUTHORIZATION.md
  test/assets/histories/openai/gpt-4.1/reddit.realize.json.gz
  test/assets/histories/openai/gpt-4.1/reddit.realize.snapshots.json.gz
Labels: documentation, enhancement

#469 feat(compiler): try catch tracing statement in controller
  packages/compiler/src/realize/writeRealizeControllers.ts
Labels: enhancement

#477 fix(ui): restore zip file download
  packages/ui/package.json
  packages/ui/src/events/AutoBeCompleteEventMovie.tsx
  pnpm-lock.yaml
Labels: bug
