Repository wrtnlabs/autobe, pull requests merged in 2025-05, with the labels that each got.

#14 Complement README content
  README.md
Labels: documentation, enhancement

#15 Add logo
  README.md
Labels: documentation

#19 Add ERDs on prisma compiler result
  packages/compiler/package.json
  packages/compiler/src/AutoBePrismaCompiler.ts
  packages/interface/src/compiler/IAutoBePrismaCompilerResult.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/src/features/compiler/test_compiler_facade_bbs.ts
  test/src/features/compiler/test_compiler_facade_shopping.ts
  test/src/features/compiler/test_compiler_prisma_correct.ts
  test/src/features/compiler/test_compiler_prisma_failure.ts
  test/src/features/compiler/test_compiler_typescript_failure.ts
  test/src/features/compiler/test_compiler_typescript_fs.ts
  test/src/features/compiler/test_compiler_typescript_migrate.ts
Labels: documentation, enhancement

#24 feat(compiler): separate compiler logic.
  packages/compiler/package.json
  packages/compiler/src/AutoBePrismaCompiler.ts
  packages/compiler/src/AutoBeTypeScriptCompiler.ts
  packages/interface/src/compiler/IAutoBePrismaCompilerResult.ts
  packages/interface/src/compiler/IAutoBeTypeScriptCompilerResult.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: documentation, enhancement

#30 feat(interface): The new OpenAPI spec only for AI
  packages/agent/build/examples.ts
  packages/agent/prompts/interface.md
  packages/agent/src/constants/AutoBeSystemPrompt.ts
  packages/agent/src/context/IAutoBeApplicationResult.ts
  packages/agent/src/factory/createAgenticaHistory.ts
  packages/agent/src/factory/createOpenApiDocument.ts
  packages/agent/src/factory/invertOpenApiDocument.ts
  packages/agent/src/orchestrate/interface/IAutoBeInterfaceApplication.ts
  packages/agent/src/orchestrate/interface/createAutoBeInterfaceApplication.ts
  packages/agent/src/orchestrate/interface/orchestrateInterface.ts
  packages/agent/src/orchestrate/interface/validateInterfaceProps.ts
  packages/interface/src/histories/AutoBeInterfaceHistory.ts
  packages/interface/src/index.ts
  packages/interface/src/openapi/AutoBeOpenApi.ts
  packages/interface/src/openapi/index.ts
  packages/interface/src/route/IAutoBeRouteBody.ts
  packages/interface/src/route/IAutoBeRouteDocument.ts
  packages/interface/src/route/IAutoBeRouteOperation.ts
  packages/interface/src/route/IAutoBeRouteParameter.ts
  packages/interface/src/route/IAutoBeRouteResponse.ts
  packages/interface/src/route/index.ts
  test/src/features/compiler/test_compiler_typescript_node.ts
Labels: documentation, enhancement

#35 feat(compiler): prettier on comments + prompt guiding
  README.md
  package.json
  packages/agent/prompts/interface.md
  packages/agent/src/AutoBeAgent.ts
  packages/agent/src/constants/AutoBeSystemPrompt.ts
  packages/agent/src/context/IAutoBeApplication.ts
  packages/agent/src/context/IAutoBeApplicationProps.ts
  packages/agent/src/factory/invertOpenApiDocument.ts
  packages/agent/src/index.ts
  packages/agent/src/orchestrate/interface/IAutoBeInterfaceApplication.ts
  packages/agent/src/orchestrate/orchestrateAnalyze.ts
  packages/agent/src/orchestrate/orchestratePrisma.ts
  packages/agent/src/structures/IAutoBeConfig.ts
  packages/compiler/package.json
  packages/compiler/src/AutoBeInterfaceCompiler.ts
  packages/interface/src/openapi/AutoBeOpenApi.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  prettier.config.js
  something.ts
Labels: documentation, enhancement

#37 feat(website): more description about roadmap schedule
  README.md
Labels: documentation, enhancement

#39 feat(agent): fixing some descriptions and prompts
  packages/agent/build/prompt.ts
  packages/agent/prompts/EXAMPLE.txt
  packages/agent/prompts/INTERFACE_ENDPOINT.md
  packages/agent/prompts/PRISMA.md
  packages/agent/prompts/PRISMA_EXAMPLE.md
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComponents.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceEndpoints.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/agent/src/orchestrate/prisma/orchestratePrisma.ts
  packages/agent/src/orchestrate/prisma/transformPrismaHistories.ts
  packages/agent/src/tools/PrismaStructuredOutput.ts
  packages/interface/src/openapi/AutoBeOpenApi.ts
Labels: documentation, enhancement

#41 feat(config): common `tsconfig.json` file
  internals/config/tsconfig.json
  internals/filesystem/tsconfig.json
  packages/agent/src/orchestrate/interface/orchestrateInterface.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComponents.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/agent/tsconfig.json
  packages/compiler/tsconfig.json
  packages/interface/tsconfig.json
  packages/rpc/tsconfig.json
  test/src/features/interface/internal/validate_agent_interface_endpoints.ts
  test/tsconfig.json
Labels: enhancement

#44 feat(agent): facade agent development
  README.md
  packages/agent/prompts/FACADE.md
  packages/agent/src/AutoBeAgent.ts
  packages/agent/src/context/IAutoBeApplication.ts
  packages/agent/src/orchestrate/facade/transformFacadeStateMessage.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComponents.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceEndpoints.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/agent/src/orchestrate/interface/transformInterfaceHistories.ts
  packages/agent/src/orchestrate/prisma/orchestratePrisma.ts
  packages/agent/src/orchestrate/prisma/transformPrismaHistories.ts
  packages/agent/src/utils/StringUtil.ts
  packages/agent/utils/IPrisma.ts
  test/src/features/compiler/test_compiler_interface_bbs.ts
  test/src/features/compiler/test_compiler_interface_shopping.ts
  test/src/features/prisma/internal/validate_agent_prisma.ts
Labels: documentation, enhancement

#46 feat(interface): more events
  README.md
  packages/interface/src/events/AutoBeEvent.ts
  packages/interface/src/events/AutoBeRealizeProgressEvent.ts
  packages/interface/src/events/AutoBeRealizeValidateEvent.ts
  packages/interface/src/events/AutoBeTestProgressEvent.ts
  packages/interface/src/events/AutoBeTestValidateEvent.ts
  packages/interface/src/events/index.ts
  packages/interface/src/json/IAutoBeEventJson.ts
  packages/interface/src/rpc/IAutoBeRpcListener.ts
  packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundProgressEventMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundValidateEventMovie.tsx
  packages/playground-ui/src/structures/AutoBePlaygroundListener.ts
Labels: documentation, enhancement

#48 feat(website): revise README
  README.md
Labels: documentation, enhancement

#49 feat(agent): dispatch analyze events
  packages/agent/src/orchestrate/orchestrateAnalyze.ts
Labels: enhancement

#51 feat(chat): real-time token usage tracing
  packages/playground-server/src/AutoBePlaygroundServer.ts
  packages/playground-ui/prompts/bbs.md
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx
Labels: enhancement

#53 fix(agent): state and history dispatching
  packages/agent/src/orchestrate/orchestrateAnalyze.ts
Labels: bug, enhancement

#55 fix(rpc): wrong import path
  packages/rpc/src/AutoBeRpcService.ts
Labels: bug, enhancement

#63 fix(rpc): event tracing on RpcService
  packages/rpc/src/AutoBeRpcService.ts
Labels: bug, enhancement

#66 Add a stackblitz button to enable analysis file inquiry
  packages/agent/src/analyze/Planning.ts
  packages/playground-ui/package.json
  packages/playground-ui/src/movies/events/AutoBePlaygroundAnalyzeWriteDocumentMovie.tsx
  pnpm-lock.yaml
Labels: bug, enhancement

#67 feat(playground-ui): detailed event components
  packages/interface/src/rpc/IAutoBeRpcService.ts
  packages/playground-ui/src/components/MarkdownViewer.tsx
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundAnalyzeWriteDocumentMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundCompleteEventMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundPrismaValidateEvent.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundValidateEventMovie.tsx
  packages/playground-ui/src/utils/ErrorUtil.ts
  packages/rpc/src/AutoBeRpcService.ts
Labels: enhancement

#69 feat(test): prepare local asset based test program
  internals/filesystem/src/RepositoryFileSystem.ts
  internals/filesystem/src/index.ts
  packages/agent/build/examples.ts
  packages/agent/build/prompt.ts
  something.ts
  test/.gitignore
  test/assets/repositories/samchon/bbs/docs/requirements/01_internal_bulletin_board_requirements_toc.md
  test/assets/repositories/samchon/bbs/docs/requirements/10_acceptance_criteria.md
  test/assets/repositories/samchon/bbs/docs/requirements/11_data_model_and_erd_high_level.md
  test/assets/repositories/samchon/bbs/docs/requirements/12_risks_and_constraints.md
  test/assets/repositories/samchon/bbs/docs/requirements/1_overview.md
  test/assets/repositories/samchon/bbs/docs/requirements/2_objectives_and_success_criteria.md
  test/assets/repositories/samchon/bbs/docs/requirements/3_user_personas.md
  test/assets/repositories/samchon/bbs/docs/requirements/4_user_journeys_and_scenarios.md
  test/assets/repositories/samchon/bbs/docs/requirements/5_functional_requirements.md
  test/assets/repositories/samchon/bbs/docs/requirements/6_non_functional_requirements.md
  test/assets/repositories/samchon/bbs/docs/requirements/7_board_structure_and_content_management.md
  test/assets/repositories/samchon/bbs/docs/requirements/8_security_and_authentication.md
  test/assets/repositories/samchon/bbs/docs/requirements/9_ui_ux_requirements.md
  test/assets/repositories/samchon/bbs/prisma/schema/main.prisma
  test/assets/repositories/samchon/shopping/docs/requirements/index.md
  test/assets/repositories/samchon/shopping/prisma/schema/main.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-01-articles.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-02-systematic.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-03-actors.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-04-sales.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-05-carts.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-06-orders.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-07-coupons.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-08-coin.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-09-inquiries.prisma
  test/assets/repositories/samchon/shopping/prisma/schema/schema-10-favorites.prisma
  test/src/features/compiler/test_compiler_facade_bbs.ts
  test/src/features/compiler/test_compiler_facade_shopping.ts
  test/src/features/compiler/test_compiler_prisma_correct.ts
  test/src/features/compiler/test_compiler_prisma_failure.ts
  test/src/features/interface/internal/prepare_agent_interface.ts
  test/src/features/prisma/internal/prepare_agent_prisma.ts
  test/src/internal/TestFileSystem.ts
Labels: enhancement

#77 feat(interface): new event type `prismaCorrect` for testing.
  packages/agent/src/orchestrate/prisma/orchestratePrismaCompiler.ts
  packages/interface/src/events/AutoBeEvent.ts
  packages/interface/src/events/AutoBePrismaCorrectEvent.ts
  packages/interface/src/events/index.ts
  packages/interface/src/json/IAutoBeEventJson.ts
  packages/interface/src/rpc/IAutoBeRpcListener.ts
  packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundPrismaCorrectEventMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundPrismaValidateEventMovie.tsx
  packages/playground-ui/src/structures/AutoBePlaygroundListener.ts
  test/src/features/prisma/internal/validate_agent_prisma.ts
Labels: documentation, enhancement

#78 feat(agent): enhance prompt of prisma about duplicate statements
  packages/agent/prompts/PRISMA_COMPILER.md
  packages/agent/prompts/PRISMA_SCHEMA.md
Labels: documentation, enhancement

#80 feat(agent): new workflow `interfaceComplement`
  packages/agent/prompts/INTERFACE_COMPLEMENT.md
  packages/agent/src/orchestrate/interface/orchestrateInterface.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComponents.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceEndpoints.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/agent/src/orchestrate/interface/transformInterfaceHistories.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaCompiler.ts
  packages/interface/src/events/AutoBeEvent.ts
  packages/interface/src/events/AutoBeInterfaceComplementEvent.ts
  packages/interface/src/events/index.ts
  packages/interface/src/json/IAutoBeEventJson.ts
  packages/playground-server/src/AutoBePlaygroundServer.ts
  packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundProgressEventMovie.tsx
  test/package.json
  test/src/features/prisma/internal/validate_agent_prisma.ts
Labels: enhancement
