Repository wrtnlabs/autobe, pull requests merged in 2025-09, with the labels that each got.

#509 fix(agent): Add kind property for checking permission hierarchy by each role.
  packages/agent/prompts/ANALYZE_SCENARIO.md
  packages/agent/prompts/INTERFACE_AUTHORIZATION.md
  packages/agent/src/orchestrate/interface/histories/transformInterfaceAuthorizationsHistories.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceAuthorizations.ts
  packages/interface/src/histories/contents/AutoBeAnalyzeRole.ts
  test/src/features/compiler/test_compiler_realize_controller.ts
  test/src/features/realize/internal/validate_agent_realize_authorization_correct.ts
Labels: documentation, enhancement

#521 feat(website): hackathon content
  website/articles/autobe-hackathon-20250913-kr.md
  website/next-env.d.ts
  website/public/images/demonstrate/replay-openai-gpt4.1-mini.png
  website/public/images/demonstrate/replay-openai-gpt4.1.png
  website/public/images/demonstrate/replay-qwen3-235b-a22b.png
  website/src/content/docs/_meta.ts
  website/src/content/docs/hackathon/index.mdx
  website/src/template/AutoBePlaygroundSection.mdx
Labels: documentation

#525 feat(website): enhance hackathon content
  website/src/content/docs/hackathon/index.mdx
Labels: documentation, enhancement

#527 feat(agent): global retry count configuration
  packages/agent/build/prompt.ts
  packages/agent/src/AutoBeAgent.ts
  packages/agent/src/constants/AutoBeConfigConstant.ts
  packages/agent/src/context/AutoBeContext.ts
  packages/agent/src/context/AutoBeTokenUsageComponent.ts
  packages/agent/src/factory/consentFunctionCall.ts
  packages/agent/src/factory/createAutoBeContext.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorizationCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/structures/IAutoBeConfig.ts
Labels: enhancement

#528 feat(agent): validate pagination response DTO
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemasReview.ts
  packages/agent/src/orchestrate/interface/structures/IAutoBeInterfaceOperationApplication.ts
  packages/agent/src/orchestrate/interface/structures/IAutoBeInterfaceOperationsReviewApplication.ts
  packages/agent/src/orchestrate/interface/utils/validateOpenApiPageSchema.ts
  packages/interface/src/openapi/AutoBeOpenApi.ts
  packages/utils/src/interface/AutoBeOpenApiTypeChecker.ts
  packages/utils/src/interface/index.ts
Labels: documentation, enhancement

#530 fix(agent): `prisma_schemas` does not exist on operation.
  packages/agent/prompts/INTERFACE_OPERATION.md
  packages/agent/prompts/INTERFACE_OPERATION_REVIEW.md
  test/src/internal/TestLogger.ts
Labels: bug

#531 fix(agent): invalid page schema validation for `IPage.IPagination` case.
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemasReview.ts
  packages/agent/src/orchestrate/interface/utils/eraseVulnerableSchemas.ts
  packages/agent/src/orchestrate/interface/utils/validateOpenApiPageSchema.ts
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.reviews.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.scenario.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.writes.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.prisma.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.prisma.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.reviews.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.scenario.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.writes.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.prisma.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.prisma.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.reviews.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.scenario.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.writes.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.prisma.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.prisma.snapshots.json.gz
  test/src/internal/TestLogger.ts
Labels: bug

#535 fix(agent): missed schema presets
  packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
  packages/agent/src/orchestrate/interface/utils/JsonSchemaFactory.ts
  test/package.json
Labels: bug, documentation, enhancement

#540 fix(agent): pagination schema composition side-effect
  packages/agent/src/orchestrate/interface/utils/JsonSchemaFactory.ts
Labels: bug, documentation, enhancement

#542 feat(agent): get reference ids from operation.
  packages/agent/src/orchestrate/test/utils/getReferenceIds.ts
Labels: documentation, enhancement

#543 feat(test): enhance test scenario related prompts
  packages/agent/prompts/TEST_CORRECT.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_WRITE.md
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.writes.json.gz
Labels: documentation, enhancement

#544 fix(agent): hallucination test scenario prompt
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/orchestrate/test/histories/transformTestScenarioHistories.ts
  packages/compiler/src/realize/testRealizeProject.ts
Labels: bug, documentation, enhancement

#547 feat(website): finalize hackathon documentation
  website/public/images/demonstrate/replay-openai-gpt4.1-mini.png
  website/public/images/hackathon/poster-20250912.png
  website/src/content/docs/hackathon/index.mdx
Labels: documentation, enhancement

#553 feat(agent): simplify test correct prompt
  packages/agent/prompts/TEST_CORRECT.md
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/orchestrate/test/compile/completeTestCode.ts
  packages/agent/src/orchestrate/test/histories/transformTestCorrectHistories.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestCorrectApplication.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestScenarioApplication.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestWriteApplication.ts
  packages/interface/src/compiler/IAutoBeTypeScriptCompileResult.ts
  test/assets/histories/openai/gpt-4.1-mini/bbs.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.writes.json.gz
  test/src/TestGlobal.ts
  test/src/archive/features/archive_test.ts
  test/src/archive/index.ts
  test/src/executable/getFiles.ts
  test/src/executable/schemas.ts
  test/src/executable/tokenUsage.ts
  test/src/features/playground/test_playground_replay_index.ts
  test/src/index.ts
Labels: documentation, enhancement

#557 feat(hackathon): complete server implementation
  apps/README.md
  apps/hackathon-api/package.json
  apps/hackathon-api/src/structures/AutoBeHackathonModel.ts
  apps/hackathon-api/src/structures/IAutoBeHackathon.ts
  apps/hackathon-api/src/structures/IAutoBeHackathonSession.ts
  apps/hackathon-api/src/structures/IAutobeHackathonParticipant.ts
  apps/hackathon-api/src/structures/index.ts
  apps/hackathon-server/.env.local
  apps/hackathon-server/.gitignore
  apps/hackathon-server/assets/participants.csv
  apps/hackathon-server/package.json
  apps/hackathon-server/prisma/schema/main.prisma
  apps/hackathon-server/src/AutoBeHackathonBackend.ts
  apps/hackathon-server/src/AutoBeHackathonConfiguration.ts
  apps/hackathon-server/src/AutoBeHackathonGlobal.ts
  apps/hackathon-server/src/controllers/participants/AutoBeHackathonParticipantAuthenticateController.ts
  apps/hackathon-server/src/controllers/participants/AutoBeHackathonParticipantSessionController.ts
  apps/hackathon-server/src/decorators/AutoBeHackathonParticipantAuth.ts
  apps/hackathon-server/src/executable/compiler.ts
  apps/hackathon-server/src/executable/schema.ts
  apps/hackathon-server/src/executable/server.ts
  apps/hackathon-server/src/providers/AutoBeHackathonParticipantProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionConnectionProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionEventProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionHistoryProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionSocketProvider.ts
  apps/hackathon-server/src/providers/acceptors/AutoBeHackathonSessionSocketAcceptor.ts
  apps/hackathon-server/src/setup/AutoBeHackathonParticipantSeeder.ts
  apps/hackathon-server/src/setup/AutoBeHackathonSeeder.ts
  apps/hackathon-server/src/setup/AutoBeHackathonSessionSeeder.ts
  apps/hackathon-server/src/setup/AutoBeHackathonSetupWizard.ts
  apps/hackathon-server/src/utils/CsvUtil.ts
  apps/hackathon-server/src/utils/JwtTokenManager.ts
  apps/hackathon-server/tsconfig.json
  apps/playground-server/src/providers/AutoBePlaygroundAcceptor.ts
  packages/agent/src/context/AutoBeTokenUsage.ts
  packages/agent/src/context/AutoBeTokenUsageComponent.ts
  packages/interface/src/rpc/IAutoBeRpcListener.ts
  packages/rpc/src/AutoBeRpcService.ts
  packages/ui/src/structure/AutoBeListener.ts
  pnpm-lock.yaml
Labels: documentation, enhancement

#554 feat(test): add candidate dependencies
  packages/agent/prompts/TEST_CORRECT.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/orchestrate/test/histories/transformTestScenarioHistories.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestCorrectApplication.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestWriteApplication.ts
Labels: documentation, enhancement

#560 feat(agent): enhance test correct prompt
  packages/agent/prompts/TEST_CORRECT.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/orchestrate/test/compile/completeTestCode.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestCorrectApplication.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestWriteApplication.ts
  pnpm-lock.yaml
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.writes.json.gz
  test/src/experimental/date.ts
  test/src/experimental/non-existing.ts
  test/src/experimental/nullable.ts
  test/src/experimental/tag.ts
  test/src/experimental/validate.ts
Labels: documentation, enhancement

#563 feat(agent): separatae test correct workflow
  packages/agent/prompts/TEST_CORRECT.md
  packages/agent/prompts/TEST_CORRECT_INVALID_REQUEST.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/orchestrate/test/histories/transformTestCorrectInvalidRequestHistories.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrectInvalidRequest.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestCorrectInvalidRequestApplication.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestCorrectTypiaTagApplication.ts
  test/assets/histories/openai/gpt-4.1-mini/bbs.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/bbs.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/reddit.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/shopping.test.writes.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.realize.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.realize.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.scenarios.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.snapshots.json.gz
  test/assets/histories/openai/gpt-4.1-mini/todo.test.writes.json.gz
Labels: bug, documentation, enhancement

#564 feat(hackathon): server implementation and test completed
  .github/workflows/build.yml
  apps/hackathon-api/package.json
  apps/hackathon-api/src/functional/autobe/hackathon/participants/authenticate/index.ts
  apps/hackathon-api/src/functional/autobe/hackathon/participants/sessions/index.ts
  apps/hackathon-api/src/module.ts
  apps/hackathon-api/src/structures/AutoBeHackathonModel.ts
  apps/hackathon-api/tsconfig.json
  apps/hackathon-server/.gitignore
  apps/hackathon-server/nestia.config.ts
  apps/hackathon-server/package.json
  apps/hackathon-server/prisma/schema/main.prisma
  apps/hackathon-server/src/controllers/participants/AutoBeHackathonParticipantAuthenticateController.ts
  apps/hackathon-server/src/controllers/participants/AutoBeHackathonParticipantSessionController.ts
  apps/hackathon-server/src/controllers/participants/AutoBeHackathonParticipantSessionSocketController.ts
  apps/hackathon-server/src/decorators/AutoBeHackathonParticipantAuth.ts
  apps/hackathon-server/src/executable/schema.ts
  apps/hackathon-server/src/providers/AutoBeHackathonParticipantProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionEventProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionHistoryProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionProvider.ts
  apps/hackathon-server/src/providers/AutoBeHackathonSessionSocketProvider.ts
  apps/hackathon-server/src/providers/acceptors/AutoBeHackathonSessionSocketAcceptor.ts
  apps/hackathon-server/src/setup/AutoBeHackathonParticipantSeeder.ts
  apps/hackathon-server/src/setup/AutoBeHackathonSeeder.ts
  apps/hackathon-server/src/setup/AutoBeHackathonSessionSeeder.ts
  apps/hackathon-server/src/setup/AutoBeHackathonSetupWizard.ts
  apps/hackathon-server/src/utils/PaginationUtil.ts
  apps/hackathon-server/test/TestAutomation.ts
  apps/hackathon-server/test/TestGlobal.ts
  apps/hackathon-server/test/features/api/test_api_hackathon_participant_login.ts
  apps/hackathon-server/test/features/api/test_api_hackathon_session_create.ts
  apps/hackathon-server/test/features/api/test_api_hackathon_session_erase.ts
  apps/hackathon-server/test/features/api/test_api_hackathon_session_replay.ts
  apps/hackathon-server/test/features/api/test_api_hackathon_session_review.ts
  apps/hackathon-server/test/features/api/test_api_hackathon_session_update.ts
  apps/hackathon-server/test/index.ts
  apps/hackathon-server/test/internal/ArgumentParser.ts
  apps/hackathon-server/test/internal/StopWatch.ts
  apps/hackathon-server/test/tsconfig.json
  apps/hackathon-server/tsconfig.json
  packages/interface/src/hackathon/AutoBeHackathonModel.ts
  packages/interface/src/hackathon/IAuthorizationToken.ts
  packages/interface/src/hackathon/IAutoBeHackathon.ts
  packages/interface/src/hackathon/IAutoBeHackathonModerator.ts
  packages/interface/src/hackathon/IAutoBeHackathonSession.ts
  packages/interface/src/hackathon/IAutoBeHackathonSessionConnection.ts
  packages/interface/src/hackathon/IAutobeHackathonParticipant.ts
  packages/interface/src/hackathon/IPage.ts
  packages/interface/src/hackathon/index.ts
  packages/interface/src/index.ts
  pnpm-lock.yaml
Labels: documentation, enhancement

#565 fix(agent): Remove Sentence of Validation Error Scenario from TEST_SCENAR…
  packages/agent/prompts/TEST_SCENARIO.md
Labels: enhancement

#574 fix(hackathon): synchronize re-connected events
  apps/hackathon-server/src/controllers/moderators/AutoBeHackathonModeratorSessionController.ts
  apps/hackathon-server/src/controllers/participants/AutoBeHackathonParticipantSessionController.ts
  apps/hackathon-server/src/providers/sessions/AutoBeHackathonSessionEventProvider.ts
  apps/hackathon-server/src/providers/sessions/acceptors/AutoBeHackathonSessionSocketAcceptor.ts
  packages/agent/src/orchestrate/interface/histories/transformInterfaceEndpointsReviewHistories.ts
  packages/agent/src/orchestrate/test/histories/transformTestCorrectHistories.ts
Labels: bug, enhancement

#575 fix(hackathon): block polling when no history at all
  apps/hackathon-server/src/providers/sessions/acceptors/AutoBeHackathonSessionSocketAcceptor.ts
Labels: bug

#603 feat(agent): new timeout strategy
  apps/hackathon-ui/src/AutoBePlaygroundApplication.tsx
  apps/hackathon-ui/src/hooks/useAuthorizationToken.ts
  apps/playground-ui/src/AutoBePlaygroundApplication.tsx
  apps/playground-ui/src/movies/replay/AutoBePlaygroundReplayGetMovie.tsx
  packages/agent/src/AutoBeAgent.ts
  packages/agent/src/AutoBeMockAgent.ts
  packages/agent/src/constants/AutoBeConfigConstant.ts
  packages/agent/src/factory/consentFunctionCall.ts
  packages/agent/src/factory/createAutoBeContext.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
  packages/agent/src/structures/IAutoBeConfig.ts
  packages/agent/src/utils/AutoBeTimeoutError.ts
  packages/agent/src/utils/TimeoutConversation.ts
  packages/agent/src/utils/registerChunkTimeout.ts
  packages/interface/src/events/AutoBeEvent.ts
  packages/interface/src/events/AutoBeEventOfSerializable.ts
  packages/interface/src/events/AutoBeJsonParseErrorEvent.ts
  packages/interface/src/events/AutoBeJsonValidateErrorEvent.ts
  packages/interface/src/events/AutoBeVendorRequestEvent.ts
  packages/interface/src/events/AutoBeVendorResponseEvent.ts
  packages/interface/src/events/AutoBeVendorTimeoutEvent.ts
  packages/ui/src/components/events/AutoBeEventMovie.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/archive.bash
  test/src/TestGlobal.ts
  test/src/archive/features/archive_analyze.ts
  test/src/archive/features/archive_interface.ts
  test/src/archive/features/archive_prisma.ts
  test/src/archive/features/archive_realize.ts
  test/src/archive/features/archive_test.ts
  test/src/archive/index.ts
  test/src/features/typings/test_typing_rpc_listener_functions.ts
  test/src/internal/TestLogger.ts
Labels: bug, documentation, enhancement

#606 feat(agent): detailed timeout configuration
  apps/hackathon-server/.env.local
  apps/hackathon-server/sql/conversations.sql
  apps/hackathon-server/src/AutoBeHackathonConfiguration.ts
  apps/hackathon-server/src/providers/sessions/acceptors/AutoBeHackathonSessionSocketAcceptor.ts
  packages/agent/src/factory/createAutoBeContext.ts
  packages/agent/src/structures/IAutoBeConfig.ts
  packages/agent/src/utils/TimedConversation.ts
  packages/interface/src/compiler/IAutoBeCompiler.ts
  packages/interface/src/compiler/IAutoBeCompilerListener.ts
  packages/interface/src/compiler/IAutoBeInterfaceCompiler.ts
  packages/interface/src/compiler/IAutoBeRealizeCompiler.ts
  packages/interface/src/compiler/IAutoBeTestCompiler.ts
  packages/interface/src/facade/IAutoBeAgent.ts
  packages/interface/src/hackathon/IAutoBeHackathon.ts
  packages/interface/src/rpc/IAutoBeRpcService.ts
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.realize.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.realize.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.test.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.test.snapshots.json.gz
  test/src/archive/index.ts
Labels: documentation, enhancement

#609 feat(test): automatic example commit system
  test/.gitignore
  test/package.json
  test/src/archive/commit.ts
  test/src/internal/TestHistory.ts
Labels: documentation, enhancement

#632 feat(website): landing page to use real replay data
  apps/playground-server/src/providers/AutoBePlaygroundReplayProvider.ts
  packages/interface/src/playground/IAutoBePlaygroundReplay.ts
  packages/utils/src/index.ts
  packages/utils/src/replay/AutoBePlaygroundReplayUtil.ts
  packages/utils/src/replay/index.ts
  pnpm-lock.yaml
  test/package.json
  test/src/archive/publish.ts
  website/package.json
  website/src/app/AutoBeLandingPage.tsx
  website/src/content/index.mdx
  website/src/data/AutoBeExperimentCollection.ts
  website/src/data/replays.json
  website/src/movies/landing/AutoBeLandingDemoMovie.tsx
  website/src/movies/landing/AutoBeLandingDemoReplayMovie.tsx
  website/src/movies/landing/AutoBeLandingHeroMovie.tsx
  website/src/movies/landing/AutoBeLandingLimitCardMovie.tsx
  website/src/movies/landing/AutoBeLandingLimitMovie.tsx
  website/src/movies/landing/AutoBeLandingMovie.tsx
  website/src/movies/landing/AutoBeLandingStrengthCardMovie.tsx
  website/src/movies/landing/AutoBeLandingStrengthMovie.tsx
  website/src/movies/landing/AutoBeLandingTechMovie.tsx
Labels: documentation, enhancement

#636 fix(website): restore beta roadmap diagram
  website/src/components/AutoBeRoadmapDiagram.tsx
  website/src/content/docs/roadmap/beta.mdx
  website/src/template/AutoBeRoadmapPreface.mdx
Labels: documentation

#650 feat(agent): make interface group description concisely.
  packages/agent/prompts/INTERFACE_GROUP.md
  packages/agent/src/orchestrate/interface/structures/IAutoBeInterfaceGroupApplication.ts
  test/src/executable/endpoints.ts
Labels: bug, documentation, enhancement

#652 feat(agent): realize agent to import every nested types
  packages/agent/src/orchestrate/realize/histories/transformRealizeWriteHistories.ts
  packages/agent/src/orchestrate/realize/orchestrateRealize.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeCorrect.ts
  packages/agent/src/orchestrate/realize/orchestrateRealizeWrite.ts
  packages/agent/src/orchestrate/realize/utils/getRealizeWriteCodeTemplate.ts
  packages/agent/src/orchestrate/realize/utils/getRealizeWriteImportStatements.ts
  packages/agent/src/orchestrate/realize/utils/replaceImportStatements.ts
  test/src/features/realize/internal/validate_agent_realize_write.ts
Labels: bug, enhancement

#653 feat(agent): concise function calling schemas.
  packages/agent/prompts/INTERFACE_COMPLEMENT.md
  packages/agent/prompts/INTERFACE_SCHEMA.md
  packages/agent/src/orchestrate/interface/structures/IAutoBeInterfaceComplementApplication.ts
  packages/agent/src/orchestrate/interface/structures/IAutoBeInterfaceSchemaApplication.ts
  test/archive.bash
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.reviews.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.scenario.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/bbs.analyze.writes.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.reviews.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.scenario.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/reddit.analyze.writes.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.reviews.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.scenario.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/shopping.analyze.writes.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/todo.analyze.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/todo.analyze.reviews.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/todo.analyze.scenario.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/todo.analyze.snapshots.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/todo.analyze.writes.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/todo.prisma.json.gz
  test/assets/histories/qwen/qwen3-235b-a22b-2507/todo.prisma.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.interface.endpoints.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.interface.groups.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.interface.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.interface.operations.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.interface.schemas.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.interface.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.realize.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.realize.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.test.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/bbs.test.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.interface.endpoints.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.interface.groups.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.interface.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.interface.operations.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.interface.schemas.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.interface.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.realize.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.realize.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.test.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/reddit.test.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.interface.groups.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.interface.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.interface.operations.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.interface.schemas.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.interface.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.realize.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.realize.snapshots.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.test.json.gz
  test/assets/histories/qwen/qwen3-next-80b-a3b-instruct/todo.test.snapshots.json.gz
  test/src/archive/features/archive_interface.ts
Labels: documentation, enhancement

#659 feat(agent): no hashed password request and none-existing timestamps.
  packages/agent/prompts/INTERFACE_SCHEMA.md
  packages/agent/prompts/INTERFACE_SCHEMA_REVIEW.md
Labels: bug, documentation, enhancement

#635 feat(interface): `AutoBeOpenApi.IOperation.prerequisites`
  packages/agent/prompts/INTERFACE_PREREQUISITE.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_SCENARIO_REVIEW.md
  packages/agent/src/AutoBeMockAgent.ts
  packages/agent/src/orchestrate/interface/histories/transformInterfaceCommonPrerequisiteHistories.ts
  packages/agent/src/orchestrate/interface/histories/transformInterfaceGroupHistories.ts
  packages/agent/src/orchestrate/interface/histories/transformInterfacePrerequisitesHistories.ts
  packages/agent/src/orchestrate/interface/orchestrateInterface.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfacePrerequisites.ts
  packages/agent/src/orchestrate/interface/structures/IAutoBeInterfacePrerequisitesApplication.ts
  packages/agent/src/orchestrate/interface/utils/OperationValidator.ts
  packages/agent/src/orchestrate/test/histories/transformTestScenarioHistories.ts
  packages/agent/src/orchestrate/test/histories/transformTestScenarioReviewHistories.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/utils/getPrerequisites.ts
  packages/agent/src/orchestrate/test/utils/getReferenceIds.ts
  packages/interface/src/events/AutoBeEvent.ts
  packages/interface/src/events/AutoBeEventSource.ts
  packages/interface/src/events/AutoBeInterfacePrerequisitesEvent.ts
  packages/interface/src/histories/contents/AutoBeInterfacePrerequisite.ts
  packages/interface/src/openapi/AutoBeOpenApi.ts
  packages/interface/src/rpc/IAutoBeRpcListener.ts
  packages/ui/src/components/events/AutoBeEventMovie.tsx
  packages/ui/src/components/events/AutoBeProgressEventMovie.tsx
  packages/ui/src/structure/AutoBeListener.ts
  packages/utils/src/interface/invertOpenApiDocument.ts
  packages/utils/src/interface/transformOpenApiDocument.ts
  test/src/features/interface/internal/validate_agent_interface_prerequisites.ts
  test/src/features/interface/test_agent_interface_prerequisites_reddit.ts
Labels: documentation
