Repository wrtnlabs/autobe, pull requests merged in 2025-06, with the labels that each got.

#85 feat(compiler): bump up nestia dependencies
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#86 feat(test): environment for test agent
  README.md
  packages/agent/src/AutoBeAgent.ts
  packages/playground-ui/src/movies/events/AutoBePlaygroundCompleteEventMovie.tsx
  test/assets/histories/bbs.analyze.json
  test/assets/histories/bbs.interface.json
  test/assets/histories/bbs.prisma.json
  test/scripts/bbs.md
  test/scripts/scenario.md
  test/scripts/shopping.md
  test/src/features/test/internal/prepare_agent_interface.ts
  test/src/features/test/test_agent_interface_asset.ts
  test/src/internal/TestHistory.ts
Labels: enhancement

#90 feat(website): change examples link
  README.md
Labels: documentation

#93 feat(agent): semaphore for limit simultaneous requests
  assets/compiler-dependencies/package-lock.json
  assets/compiler-dependencies/package.json
  packages/agent/src/AutoBeAgent.ts
  packages/agent/src/context/AutoBeContext.ts
  packages/agent/src/factory/createAgenticaHistory.ts
  packages/agent/src/orchestrate/analyze/AutoBeAnalyzeAgent.ts
  packages/agent/src/orchestrate/analyze/AutoBeAnalyzeReviewer.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComponents.ts
  packages/agent/src/orchestrate/interface/transformInterfaceHistories.ts
  packages/agent/src/orchestrate/prisma/transformPrismaComponentsHistories.ts
  packages/agent/src/orchestrate/prisma/transformPrismaCorrectHistories.ts
  packages/agent/src/orchestrate/prisma/transformPrismaHistories.ts
  packages/agent/src/orchestrate/prisma/transformPrismaSchemaHistories.ts
  packages/agent/src/structures/IAutoBeVendor.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#94 feat(website): initial setup
  .github/workflows/website.yml
  .vscode/settings.json
  packages/agent/typedoc.json
  packages/compiler/typedoc.json
  packages/interface/typedoc.json
  packages/rpc/typedoc.json
  pnpm-lock.yaml
  website/.gitignore
  website/build/deploy.js
  website/build/typedoc.js
  website/next-env.d.ts
  website/next-sitemap.config.js
  website/next.config.mjs
  website/package.json
  website/pages/_app.js
  website/pages/_meta.js
  website/pages/docs/_meta.js
  website/pages/docs/agent/_meta.js
  website/pages/docs/agent/config.mdx
  website/pages/docs/agent/event.mdx
  website/pages/docs/agent/history.mdx
  website/pages/docs/agent/index.mdx
  website/pages/docs/backend/_meta.js
  website/pages/docs/backend/e2e.mdx
  website/pages/docs/backend/index.mdx
  website/pages/docs/backend/nestjs.mdx
  website/pages/docs/backend/prisma.mdx
  website/pages/docs/concepts/_meta.js
  website/pages/docs/concepts/compiler.mdx
  website/pages/docs/concepts/openapi.mdx
  website/pages/docs/concepts/waterfall.mdx
  website/pages/docs/index.mdx
  website/pages/docs/related/_meta.js
  website/pages/docs/related/agentica.mdx
  website/pages/docs/related/autoview.mdx
  website/pages/docs/roadmap.mdx
  website/pages/docs/setup.mdx
  website/pages/docs/websocket/_meta.js
  website/pages/docs/websocket/client.mdx
  website/pages/docs/websocket/index.mdx
  website/pages/docs/websocket/nestjs.mdx
  website/pages/docs/websocket/nodejs.mdx
  website/pages/index.mdx
  website/public/.nojekyll
  website/public/logo.png
  website/public/og.jpg
  website/theme.config.tsx
  website/tsconfig.json
  website/typedoc.json
Labels: documentation

#100 feat(website): waterfall model concept
  website/.gitignore
  website/pages/docs/concepts/waterfall.mdx
  website/template/snippet/AutoBeSnippetInterfaceShoppingController.mdx
  website/template/snippet/AutoBeSnippetInterfaceShoppingDto.mdx
  website/template/snippet/AutoBeSnippetInterfaceShoppingTest.mdx
  website/theme.config.tsx
Labels: documentation

#101 feat(website): add compiler concept page
  website/build/sitemap.js
  website/package.json
  website/pages/docs/concepts/_meta.js
  website/pages/docs/concepts/compiler.mdx
  website/pages/docs/concepts/openapi.mdx
  website/pages/docs/concepts/waterfall.mdx
  website/pages/docs/roadmap.mdx
  website/template/diagrams/AutoBeWaterfallDiagram.mdx
  website/template/snippets/AutoBeInterfaceShoppingControllerSnippet.mdx
  website/template/snippets/AutoBeInterfaceShoppingDtoSnippet.mdx
  website/template/snippets/AutoBeInterfaceShoppingTestSnippet.mdx
Labels: documentation

#103 feat(website): official release plan
  website/pages/docs/_meta.js
  website/pages/docs/roadmap/_meta.js
  website/pages/docs/roadmap/alpha.mdx
  website/pages/docs/roadmap/beta.mdx
  website/pages/docs/roadmap/v1.0.mdx
Labels: documentation

#104 feat(website): add snapshot plan
  website/pages/docs/roadmap/beta.mdx
  website/pages/docs/websocket/index.mdx
  website/template/AutoBeRoadmapPreface.mdx
Labels: documentation

#107 fix: Add Test Validate Event to Playground
  packages/interface/src/rpc/IAutoBeRpcListener.ts
  packages/playground-ui/src/structures/AutoBePlaygroundListener.ts
  packages/rpc/src/AutoBeRpcService.ts
Labels: enhancement

#110 feat(website): pagefind
  pnpm-lock.yaml
  website/package.json
Labels: documentation

#111 fix(agent): life checking on prisma corrector.
  packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
  packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
Labels: bug

#114 feat(compiler): gin index validation.
  packages/compiler/src/prisma/validatePrismaApplication.ts
  test/src/features/compiler/examples/prisma.gin.json
  test/src/features/compiler/test_compiler_prisma_gin.ts
Labels: enhancement

#115 feat(playground-ui): download button
  packages/playground-ui/package.json
  packages/playground-ui/src/movies/events/AutoBePlaygroundCompleteEventMovie.tsx
  pnpm-lock.yaml
Labels: documentation, enhancement

#125 feat(website): README and ecosystem revising
  README.md
  website/content/docs/_meta.ts
  website/content/docs/agent/_meta.ts
  website/content/docs/ecosystem.mdx
  website/content/docs/index.mdx
  website/content/docs/roadmap/_meta.ts
  website/content/docs/stack/_meta.ts
  website/content/docs/stack/index.mdx
  website/content/docs/stack/nestjs.mdx
  website/content/docs/stack/openapi.mdx
  website/content/docs/stack/prisma.mdx
  website/content/docs/websocket/_meta.ts
  website/content/index.mdx
  website/public/images/ghibli-like-diagram.png
  website/template/AutoBeEcosystemPreface.mdx
  website/template/AutoBeIntroductionPreface.mdx
  website/template/AutoBePlaygroundSection.mdx
  website/template/AutoBeRoadmapPreface.mdx
Labels: documentation

#127 feat(website): ecosystem chapter
  README.md
  typos.toml
  website/content/docs/stack/_meta.ts
  website/content/docs/stack/nestjs.mdx
  website/content/docs/stack/prisma.mdx
  website/content/docs/stack/typescript.mdx
  website/public/images/prisma-wide-logo.png
  website/public/images/typescript-wide-logo.png
  website/public/logo.png
  website/public/og.jpg
  website/template/AutoBeIntroductionPreface.mdx
  website/template/diagrams/AutoBeWaterfallDiagram.mdx
Labels: documentation, enhancement

#132 feat(interface): documentation comments
  README.md
  packages/interface/src/compiler/IAutoBePrismaCompilerResult.ts
  packages/interface/src/events/AutoBeAnalyzeCompleteEvent.ts
  packages/interface/src/events/AutoBeAnalyzeReviewEvent.ts
  packages/interface/src/events/AutoBeAnalyzeStartEvent.ts
  packages/interface/src/events/AutoBeAnalyzeWriteEvent.ts
  packages/interface/src/events/AutoBeAssistantMessageEvent.ts
  packages/interface/src/events/AutoBeInterfaceComplementEvent.ts
  packages/interface/src/events/AutoBeInterfaceCompleteEvent.ts
  packages/interface/src/events/AutoBeInterfaceComponentsEvent.ts
  packages/interface/src/events/AutoBeInterfaceEndpointsEvent.ts
  packages/interface/src/events/AutoBeInterfaceOperationsEvent.ts
  packages/interface/src/events/AutoBeInterfaceStartEvent.ts
  packages/interface/src/events/AutoBePrismaCompleteEvent.ts
  packages/interface/src/events/AutoBePrismaComponentsEvent.ts
  packages/interface/src/events/AutoBePrismaCorrectEvent.ts
  packages/interface/src/events/AutoBePrismaSchemasEvent.ts
  packages/interface/src/events/AutoBePrismaStartEvent.ts
  packages/interface/src/events/AutoBePrismaValidateEvent.ts
  packages/interface/src/events/AutoBeRealizeCompleteEvent.ts
  packages/interface/src/events/AutoBeRealizeProgressEvent.ts
  packages/interface/src/events/AutoBeRealizeStartEvent.ts
  packages/interface/src/events/AutoBeRealizeValidateEvent.ts
  packages/interface/src/events/AutoBeTestCompleteEvent.ts
  packages/interface/src/events/AutoBeTestCorrectEvent.ts
  packages/interface/src/events/AutoBeTestProgressEvent.ts
  packages/interface/src/events/AutoBeTestStartEvent.ts
  packages/interface/src/events/AutoBeTestValidateEvent.ts
  packages/interface/src/events/AutoBeUserMessageEvent.ts
  packages/interface/src/histories/AutoBeAnalyzeHistory.ts
  packages/interface/src/histories/AutoBeAssistantMessageHistory.ts
  packages/interface/src/histories/AutoBeHistory.ts
  packages/interface/src/histories/AutoBeHistoryBase.ts
  packages/interface/src/histories/AutoBeInterfaceHistory.ts
  packages/interface/src/histories/AutoBePrismaHistory.ts
  packages/interface/src/histories/AutoBeRealizeHistory.ts
  packages/interface/src/histories/AutoBeTestHistory.ts
  packages/interface/src/histories/AutoBeUserMessageHistory.ts
  packages/interface/src/histories/contents/AutoBeUserMessageAudioContent.ts
  packages/interface/src/histories/contents/AutoBeUserMessageContent.ts
  packages/interface/src/histories/contents/AutoBeUserMessageContentBase.ts
  packages/interface/src/histories/contents/AutoBeUserMessageFileContent.ts
  packages/interface/src/histories/contents/AutoBeUserMessageImageContent.ts
  packages/interface/src/histories/contents/AutoBeUserMessageTextContent.ts
  packages/interface/src/json/IAutoBeTokenUsageJson.ts
  packages/interface/src/rpc/IAutoBeRpcHeader.ts
  packages/interface/src/rpc/IAutoBeRpcListener.ts
  packages/interface/src/rpc/IAutoBeRpcService.ts
  packages/interface/src/rpc/IAutoBeRpcVendor.ts
Labels: documentation, enhancement

#133 feat(compiler): documentation and refactoring.
  packages/agent/build/prompt.ts
  packages/agent/src/AutoBeAgent.ts
  packages/agent/src/factory/index.ts
  packages/agent/src/orchestrate/interface/orchestrateInterface.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/structures/IAutoBeConfig.ts
  packages/agent/src/structures/IAutoBeProps.ts
  packages/agent/src/structures/IAutoBeVendor.ts
  packages/compiler/src/AutoBeCompiler.ts
  packages/compiler/src/AutoBeInterfaceCompiler.ts
  packages/compiler/src/AutoBePrismaCompiler.ts
  packages/compiler/src/AutoBeTypeScriptCompiler.ts
  packages/interface/src/compiler/IAutoBeCompiler.ts
  packages/interface/src/compiler/IAutoBeInterfaceCompiler.ts
  packages/interface/src/compiler/IAutoBePrismaCompiler.ts
  packages/interface/src/compiler/IAutoBePrismaCompilerProps.ts
  packages/interface/src/compiler/IAutoBeTypeScriptCompiler.ts
  packages/interface/src/compiler/IAutoBeTypeScriptCompilerProps.ts
  packages/interface/src/compiler/IAutoBeTypeScriptCompilerResult.ts
  packages/interface/src/events/AutoBeAnalyzeCompleteEvent.ts
  packages/interface/src/events/AutoBeAnalyzeReviewEvent.ts
  packages/interface/src/events/AutoBeAnalyzeStartEvent.ts
  packages/interface/src/events/AutoBeAnalyzeWriteEvent.ts
  packages/interface/src/events/AutoBeTestProgressEvent.ts
  packages/interface/src/events/AutoBeTestValidateEvent.ts
  packages/rpc/src/AutoBeRpcService.ts
  test/src/features/compiler/test_compiler_facade_bbs.ts
  test/src/features/compiler/test_compiler_facade_shopping.ts
  test/src/features/compiler/test_compiler_interface_bbs.ts
  test/src/features/compiler/test_compiler_interface_shopping.ts
  test/src/features/interface/internal/prepare_agent_interface.ts
  test/src/features/test/internal/prepare_agent_test_main.ts
Labels: documentation, enhancement

#135 fix(compiler): paths with baseUrl
  packages/compiler/src/AutoBeTypeScriptCompiler.ts
  test/src/features/compiler/test_compiler_typescript_alias.ts
Labels: bug

#144 feat(website): documentation about generated artifacts
  README.md
  packages/agent/src/AutoBeAgent.ts
  packages/interface/src/rpc/IAutoBeGetFilesOptions.ts
  packages/interface/src/rpc/IAutoBeRpcService.ts
  packages/rpc/src/AutoBeRpcService.ts
  website/content/docs/agent/_meta.ts
  website/content/docs/agent/facade.mdx
  website/content/docs/websocket/_meta.ts
  website/content/docs/websocket/rpc.mdx
  website/template/declarations/AutoBeAgentDeclaration.mdx
  website/template/snippets/AutoBeAgentGetFilesSnippet.mdx
Labels: documentation, enhancement

#146 fix(agent): semaphore sharing
  packages/agent/src/AutoBeAgent.ts
Labels: bug

#149 feat(interface): refactor events
  .gitignore
  packages/agent/prompts/ANALYZE.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/src/orchestrate/test/orchestrateTest.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestProgress.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestScenarioApplication.ts
  packages/agent/src/orchestrate/test/transformTestProgressHistories.ts
  packages/interface/src/events/AutoBeEvent.ts
  packages/interface/src/events/AutoBeTestPlanEvent.ts
  packages/interface/src/events/AutoBeTestScenarioEvent.ts
  packages/interface/src/events/AutoBeTestValidateEvent.ts
  packages/interface/src/events/AutoBeTestWriteEvent.ts
  packages/interface/src/events/index.ts
  packages/interface/src/index.ts
  packages/interface/src/rpc/IAutoBeRpcListener.ts
  packages/interface/src/test/AutoBeTestScenario.ts
  packages/interface/src/test/index.ts
  packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
  packages/playground-ui/src/movies/events/AutoBePlaygroundProgressEventMovie.tsx
  packages/playground-ui/src/structures/AutoBePlaygroundListener.ts
  test/assets/repositories/samchon/bbs-backend/test/codes.json
  test/assets/repositories/samchon/bbs-backend/test/correct_files.json
  test/assets/repositories/samchon/bbs-backend/test/plans.json
  test/assets/repositories/samchon/shopping-backend/test/codes.json
  test/assets/repositories/samchon/shopping-backend/test/plans.json
  test/src/features/test/internal/validate_agent_test.ts
  test/src/features/test/internal/validate_agent_test_correct.ts
  test/src/features/test/internal/validate_agent_test_scenario.ts
  test/src/features/test/internal/validate_agent_test_write.ts
  test/src/features/test/test_agent_test_plan_bbs.ts
  test/src/features/test/test_agent_test_plan_shopping.ts
  test/src/features/test/test_agent_test_progress_bbs.ts
  test/src/features/test/test_agent_test_progress_shopping.ts
  test/src/features/test/test_agent_test_scenario_bbs.ts
  test/src/features/test/test_agent_test_scenario_shopping.ts
  test/src/features/test/test_agent_test_write_bbs.ts
  test/src/features/test/test_agent_test_write_shopping.ts
  website/content/docs/agent/event.mdx
Labels: documentation, enhancement

#150 feat(playground): add semaphore input
  packages/interface/src/rpc/IAutoBeRpcVendor.ts
  packages/playground-server/src/executable/server.ts
  packages/playground-ui/src/movies/chat/AutoBePlaygroundChatSideMovie.tsx
  packages/playground-ui/src/movies/configure/AutoBePlaygroundConfigureMovie.tsx
  packages/playground-ui/src/movies/configure/AutoBePlaygroundConfigureVendorMovie.tsx
Labels: documentation, enhancement

#151 feat(agent): enforce file generation even compilation failed
  packages/agent/src/AutoBeAgent.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
Labels: documentation, enhancement

#153 feat(agent): enhance test code writer prompt.
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/orchestrate/test/compileTestScenario.ts
  packages/agent/src/orchestrate/test/orchestrateTest.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestScenarioArtifacts.ts
  packages/agent/src/orchestrate/test/transformTestCorrectHistories.ts
  packages/agent/src/orchestrate/test/transformTestWriteHistories.ts
  test/src/features/test/internal/validate_agent_test_write.ts
Labels: documentation, enhancement

#154 feat(agent): enhance test code writer prompt.
  README.md
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/orchestrate/test/filterTestFileName.ts
  packages/agent/src/orchestrate/test/orchestrateTest.ts
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
  packages/interface/src/events/AutoBeRealizeCompleteEvent.ts
  packages/interface/src/events/AutoBeTestCompleteEvent.ts
  packages/playground-ui/src/movies/events/AutoBePlaygroundCompleteEventMovie.tsx
  test/src/features/test/internal/compiled-histories.json
  test/src/features/test/test_agent_test_compile.ts
  website/template/AutoBePlaygroundSection.mdx
Labels: bug, enhancement

#156 fix(agent): test scenario prompt
  packages/agent/prompts/TEST_CORRECT.md
  packages/agent/prompts/TEST_SCENARIO.md
  packages/agent/prompts/TEST_TYPESCRIPT_SYNTAX.md
  packages/agent/prompts/TEST_VALIDATOR.md
  packages/agent/prompts/TEST_WRITE.md
  packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
  packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
  packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
  packages/agent/src/orchestrate/test/structures/IAutoBeTestScenarioApplication.ts
  packages/agent/src/orchestrate/test/transformTestCorrectHistories.ts
  packages/agent/src/orchestrate/test/transformTestWriteHistories.ts
  test/assets/repositories/samchon/bbs-backend/test/scenarios.json
Labels: enhancement

#164 feat(website): folder restructuring
  pnpm-workspace.yaml
  website/src/app/[[...mdxPath]]/page.jsx
  website/src/app/layout.jsx
  website/src/components/LocalSource.tsx
  website/src/components/LocalSourceGroup.tsx
  website/src/components/RemoteSource.tsx
  website/src/components/RemoteSourceGroup.tsx
  website/src/components/internal/getLocalSourceFile.ts
  website/src/content/_meta.ts
  website/src/content/docs/_meta.ts
  website/src/content/docs/agent/_meta.ts
  website/src/content/docs/agent/config.mdx
  website/src/content/docs/agent/event.mdx
  website/src/content/docs/agent/facade.mdx
  website/src/content/docs/agent/history.mdx
  website/src/content/docs/concepts/_meta.ts
  website/src/content/docs/concepts/compiler.mdx
  website/src/content/docs/concepts/function-calling.mdx
  website/src/content/docs/concepts/waterfall.mdx
  website/src/content/docs/ecosystem.mdx
  website/src/content/docs/index.mdx
  website/src/content/docs/roadmap/_meta.ts
  website/src/content/docs/roadmap/alpha.mdx
  website/src/content/docs/roadmap/beta.mdx
  website/src/content/docs/roadmap/v1.0.mdx
  website/src/content/docs/setup.mdx
  website/src/content/docs/stack/_meta.ts
  website/src/content/docs/stack/nestjs.mdx
  website/src/content/docs/stack/prisma.mdx
  website/src/content/docs/stack/typescript.mdx
  website/src/content/docs/websocket/_meta.ts
  website/src/content/docs/websocket/client.mdx
  website/src/content/docs/websocket/nestjs.mdx
  website/src/content/docs/websocket/nodejs.mdx
  website/src/content/docs/websocket/rpc.mdx
  website/src/content/index.mdx
  website/src/template/AutoBeEcosystemPreface.mdx
  website/src/template/AutoBeIntroductionPreface.mdx
  website/src/template/AutoBePlaygroundSection.mdx
  website/src/template/AutoBeRoadmapPreface.mdx
  website/src/template/diagrams/AutoBeWaterfallDiagram.mdx
  website/src/template/snippets/AutoBeEcosystemAgenticaSnippet.mdx
  website/src/template/snippets/AutoBeInterfaceShoppingControllerSnippet.mdx
  website/src/template/snippets/AutoBeInterfaceShoppingDtoSnippet.mdx
  website/src/template/snippets/AutoBeInterfaceShoppingTestSnippet.mdx
  website/src/template/snippets/AutoBeRpcClientSetupSnippet.mdx
  website/src/template/snippets/AutoBeRpcNestJsSetupSnippet.mdx
  website/src/template/snippets/AutoBeRpcNodeJsSetupSnippet.mdx
Labels: documentation

#170 feat(compiler): `AutoBeTestCompiler.compile()`.
  README.md
  packages/compiler/src/AutoBeCompiler.ts
  packages/compiler/src/AutoBeTestCompiler.ts
  packages/compiler/src/test/IAutoBeTestProgrammerContext.ts
  packages/compiler/src/test/programmers/AutoBeTestAccessorProgrammer.ts
  packages/compiler/src/test/programmers/AutoBeTestFunctionalProgrammer.ts
  packages/compiler/src/test/programmers/AutoBeTestLiteralProgrammer.ts
  packages/compiler/src/test/programmers/AutoBeTestRandomProgrammer.ts
  packages/compiler/src/test/programmers/AutoBeTestStatementProgrammer.ts
  packages/compiler/src/test/writeTestExpression.ts
  packages/compiler/src/test/writeTestFunction.ts
  packages/compiler/src/test/writeTestStatement.ts
  packages/compiler/src/utils/FilePrinter.ts
  packages/interface/src/compiler/IAutoBeCompiler.ts
  packages/interface/src/compiler/IAutoBeTestCompiler.ts
  packages/interface/src/compiler/IAutoBeTestCompilerProps.ts
  packages/interface/src/compiler/index.ts
  packages/interface/src/index.ts
  packages/interface/src/test/AutoBeTest.ts
  packages/interface/src/test/index.ts
  website/src/template/AutoBeRoadmapPreface.mdx
Labels: enhancement
